# Generated by Django 2.2 on 2020-05-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='mails',
            name='sender',
            field=models.CharField(default='xyz', max_length=30),
        ),
        migrations.AddField(
            model_name='mails',
            name='sop',
            field=models.CharField(default='dummy', max_length=300),
        ),
        migrations.AddField(
            model_name='mails',
            name='title',
            field=models.CharField(default='dummy', max_length=300),
        ),
    ]
