# Generated by Django 2.2 on 2020-05-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20200516_2211'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, default='course-1.jpg', max_length=20, null=True),
        ),
        
    ]
