# Generated by Django 2.2 on 2020-05-30 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20200530_1635'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, default='assets/img/course-1.jpg', max_length=20, null=True),
        ),
       
    ]
