# Generated by Django 2.2 on 2020-05-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20200530_1644'),
    ]

    operations = [
        
        
       
    ]
