# Generated by Django 2.2 on 2020-05-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20200530_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        
    ]
