# Generated by Django 2.2 on 2020-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_auto_20200530_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='image',
            field=models.CharField(blank=True, default='assets/img/course-1.jpg', max_length=20, null=True),
        ),
    ]
