# Generated by Django 2.2 on 2020-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0008_auto_20200530_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='image_webinar',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
