# Generated by Django 2.2 on 2020-05-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0009_auto_20200530_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='for_everybody',
            new_name='for_everybody_webinar',
        ),
    ]
