# Generated by Django 2.2 on 2020-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0010_auto_20200530_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='image_webinar',
            field=models.IntegerField(default=0, max_length=20, null=True),
        ),
    ]
