# Generated by Django 2.2 on 2020-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0011_auto_20200530_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='webinar_author_name',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
