# Generated by Django 2.2 on 2020-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0012_webinar_webinar_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='cost',
        ),
        migrations.AddField(
            model_name='webinar',
            name='cost_webinar',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='image_webinar',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
